log_level: "Debug" #Info/Warn/Error
storage:
  db_user: "username"
  db_password: "password"
  db_address: "container_db_name:5432"
  db_name: "db_name"
  db_ssl_mode: "disable"
http_server:
  server_address: "container_app_name:9090"
  server_timeout: 4s
  server_idle_timeout: 60s
  token_expiration_time_minutes: 5
  jwt_key: "my_big_not_simple_key"
side_api_url:
  get_cities_url: "cities_url"
  get_weather_url: "weather_url"
  api_key: "your_Key"
